version: '3.4'

services: 
  sourcingdb:
    image: mongo
  e-sourcingproducts:
    image: ${DOCKER_REGISTRY-}esourcingproducts
    build:
      context: .
      dockerfile: ESourcing.Products/Dockerfile
