version: '3.4'

services:
  sourcingdb: 
    container_name: sourcingdb 
    restart: always 
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
        #- ./data:/data/db
    ports:
        - "27017:27017"
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
       - "5672:5672"
       - "15672:15672"
  e-sourcingproducts: 
    container_name: esourcingproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
    depends_on:
        - sourcingdb
    volumes:
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
    ports:
      - "8000:80"
  sourcingsqldb:
    container_name: sourcingsqldb
    ports:
      - "1433:1433"
    environment:
       SA_PASSWORD: "Odb12345678"
       ACCEPT_EULA: "Y"
  esourcing.sourcing: 
    container_name: esourcingsourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - sourcingdb
      - rabbitmq
    volumes:
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
    ports:
      - "8001:80"


  esourcing.order:
    container_name: esourcingorder
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnection=Server=sourcingsqldb;Database=OrderDb;User Id=sa;Password=Odb12345678"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - sourcingsqldb
      - rabbitmq
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8002:80"

